apiVersion: v1
kind: Pod
metadata:
  labels:
    run: multi-log-pod
  name: multi-log-pod
spec:
  containers:
  - image: busybox
    name: logger-a
    resources: {}
    command: ['/bin/sh', '-c']
    args: ["while true; do echo 'Log A: $(date)' >> /var/log/app.log; sleep 5; done"]
    volumeMounts:
        - name: log-volume
          mountPath: /var/log
  - image: busybox
    name: logger-b
    command: ['/bin/sh', '-c']
    args: ["while true; do echo 'Log B: $(date)' >> /var/log/app.log; sleep 5; done"]
    volumeMounts:
        - name: log-volume
          mountPath: /var/log
  volumes:
    - name: log-volume
      hostPath:
        path: /var/log
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
