apiVersion: v1
kind: Pod
metadata:
  name: multi-pod-1
spec:
  containers:
    - name: frontend
      image: nginx:latest
    - name: backend
      image: busybox:latest
      env:
        - name: APP_MODE
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: APP_MODE
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
      command: ["sleep", "3600"]
      volumeMounts:
      - name: app-config-volume
        mountPath: /etc/config
      - name: db-secret-volume
        mountPath: /etc/secret
  volumes:
    - name: app-config-volume
      configMap:
        name: app-config
    - name: db-secret-volume
      secret:
        secretName: db-secret  


  

