apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web
  name: web-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-deploy
  strategy: {}
  template:
    metadata:
      labels:
        app: web-deploy
    spec:
      containers:
      - image: nginx:1.19
        name: nginx1
        ports:
        - containerPort : 80
        resources: {}
status: {}

