apiVersion: v1
kind: Pod
metadata:
  name: web-server
  labels:
    app: web-server
spec:
      containers:
        - name: nginx-container
          image: nginx
          volumeMounts:
            - name: shared-data
              mountPath: /usr/share/nginx/html
      initContainers:
        - name: adapter-container
          image: busybox
          restartPolicy: Always
          command: ["/bin/sh", "-c", "while true; do date > /data/index.html; sleep 10; done"]
          volumeMounts:
            - name: shared-data
              mountPath: /data
      volumes:
        - name: shared-data
          emptyDir: {}