apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backend-api
  name: backend-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-api
  strategy: {}
  template:
    metadata:
      labels:
        app: backend-api
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 8080
        resources: {}
status: {}
