apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: my-app-deploy
  name: my-app-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app-deploy
  strategy: {}
  template:
    metadata:
      labels:
        app: my-app-deploy
    spec:
      containers:
      - image: nginx:latest
        name: nginx
        resources: 
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
	env: 
	 - name: APP_LOG_LEVEL
           valueFrom:
             configMapKeyRef:
               name: app-settings
               key: log_level
status: {}
