apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: data-server
  namespace: ckad-q3-stateful
spec:
  selector:
    matchLabels:
      app: mongo 
  serviceName: "mongo"
  replicas: 3 
  minReadySeconds: 10 
  template:
    metadata:
      labels:
        app: mongo 
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mongo
        image: mongo:4.0
        volumeMounts:
        - name: mongo-data
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: mongo-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      # storageClassName: "my-storage-class"
      resources:
        requests:
          storage: 500Mi